accounts/urls.py
#coding: utf-8
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from accounts.views import *
from catalog.views import *
from delivery.views import *


urlpatterns = patterns('',
    url(r'^$', login_required(account_index), name='account_index'),
    url(r'^parts/$', login_required(PartsView.as_view(template_name='accounts/parts.html')), name='account_parts'),
    url(r'^auth/$', authentication, name='account_auth'),
    url(r'^login/$', user_login, name='account_login'),
    url(r'^parts/(?P<slug>[-_\w]+)/$', login_required(PartDetailView.as_view()), name='account_partsdetail'),
    url(r'^order/$', login_required(order_view), name='account_delivery'),
    url(r'^order/detail_order/(?P<pk>[-_\w]+)/$', login_required(OrderDetail.as_view()), name='account_order_detail'),
    url(r'^logout/$', LogOutView.as_view(), name='logout'),
    url(r'^registration/$', registration, name='account_registration'),
    url(r'^cart/$', show_cart, name='show_cart'),
    url(r'^ajax_add_to_cart/$', ajax_add_to_cart, name='ajax_add_to_cart'),
    url(r'^ajax_add_cart/$', ajax_add_to_cart, name='ajax_add_cart'),
    url(r'^get_message/(?P<pk>[-_\w]+)/$', login_required(get_messages), name='get_message'),
    url(r'^ajax_delete_to_cart/$', ajax_delete_to_cart, name='ajax_delete_to_cart'),
    url(r'^checkout_cart/$', login_required(checkout_cart), name='checkout_cart'),
    url(r'^ajax_plus_to_cart/$', ajax_plus_to_cart, name='ajax_plus_to_cart'),
    url(r'^ajax_minus_to_cart/$', ajax_minus_to_cart, name='ajax_minus_to_cart'),
    url(r'^dialogs/$', login_required(DialogsView.as_view(template_name='accounts/dialogs.html')), name='account_dialogs'),
    url(r'^chat/(?P<pk>[-_\w]+)/$', login_required(chat_view), name='chat'),
    url(r'^chat_control/(?P<u_pk>[-_\w]+)/$', login_required(chat_control_view), name='chat_control'),
    url(r'^public_chat/$', login_required(public_chat_view), name='public_chat'),
    url(r'^ajax_search_user/$', search_user_view, name='search_user'),
    url(r'^chat_add_user/(?P<pk>[-_\w]+)/(?P<u_pk>[-_\w]+)/$', chat_add_user_view, name='chat_add_user'),
    url(r'^set_chat_title/(?P<pk>[-_\w]+)/$', set_chat_title_view, name='set_chat_title'),
    url(r'^ajax_badge_cart/$', ajax_badge_cart, name='ajax_badge_cart'),
    url(r'^add_part/$', login_required(part_add), name='part_add'),
    url(r'^blog/(?P<u_pk>[-_\w]+)/$', login_required(post_list_view), name='blog_list'),
    url(r'^blog/(?P<slug>[-_\w]+)/$', login_required(post_detail_view), name='post_detail'),
    url(r'^blog_new/(?P<slug>[-_\w]+)/$', login_required(add_post_view), name='new_post'),
    url(r'^post_event/(?P<pk>[-_\w]+)/(?P<event>[-_\w]+)/$', login_required(post_event_view), name='post_event'),
    url(r'^comments/', include("django.contrib.comments.urls")),
    url(r'^part_delivery/', login_required(part_delivery), name='part_delivery'),
    url(r'^edit_data/(?P<data>[-_\w]+)/$', login_required(edit_data_view), name='edit_data'),
    url(r'^edit_address/(?P<pk>[-_\w]+)/$', login_required(edit_address_view), name='edit_address'),
    url(r'^delete_address/(?P<pk>[-_\w]+)/$', login_required(delete_address_view), name='delete_address'),
    url(r'^validation_cart/$', login_required(ajax_validation_cart), name='ajax_validation_cart'),
)

catalog/urls.py
#coding: utf-8
from django.conf.urls import patterns, url
from catalog.views import *

urlpatterns = patterns('',
    url(r'^search_part/$', search_by_article, name='search_by_article'),
    url(r'^(?P<slug>[-_\w]+)/$', part_detail, name='catalog_part_detail'),
    url(r'^$', part_list_view, name='catalog_part')
)

partcom/urls.py
from django.conf.urls import *

from django.contrib import admin
from accounts.views import SSE, PostsListView, post_detail_view, post_list_view, index_view


admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', index_view, name='index'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^catalog/', include('catalog.urls')),
    url(r'^account/', include('accounts.urls')),
    url(r'^sse/(?P<channel>\w+)/$', SSE.as_view(redis_channel='main_channel'), name='sse_main_channel'),
    url(r'^blogs/$', PostsListView.as_view(), name='blogs_list'),
    url(r'^blogs/(?P<u_pk>[-_\w]+)/(?P<slug>[-_\w]+)/$', post_detail_view, name='posts_detail'),
    url(r'^blogs/(?P<u_pk>[-_\w]+)/$', post_list_view, name='user_blog'),
    url(r'^ckeditor/', include('ckeditor.urls')),
)

accounts/models.py
#coding: utf-8
from django.db import models
from django.contrib.auth.models import User
from catalog.models import *
from datetime import datetime

COUNTRY_CHOICES = (
    ('KZ', 'Казахстан'),
)

REGION_CHOICES = (
    ('VKO', 'Восточно-Казахстанская область'),
)

CITY_CHOICES = (
    ('UKG', 'Усть-Каменогорск'),
)


class Address(models.Model):
    country = models.CharField(verbose_name='Страна', max_length=3, choices=COUNTRY_CHOICES, default='KZ')
    region = models.CharField(verbose_name='Область', max_length=4, choices=REGION_CHOICES, default='VKO')
    city = models.CharField(verbose_name='Город', max_length=100, choices=CITY_CHOICES, default='UKG')
    address = models.CharField(verbose_name='Адрес', max_length=100)
    address_index = models.CharField(verbose_name='Индекс', max_length=10, default='070000')
    phones = models.CharField(verbose_name='Телефоны', max_length=100, default='')
    details = models.CharField(verbose_name='Примечания', max_length=1000, null=True, blank=True, default='')

    class Meta:
        verbose_name = 'адрес'
        verbose_name_plural = 'адреса'
        ordering = ['country', 'region', 'city', 'address', 'pk']

    def __unicode__(self):
        return self.address


ACCOUNT_TYPES = (
    (1, u'Покупатель'),
    (2, u'Продавец'),
)


class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='profile', verbose_name='Профиль')
    addresses = models.ManyToManyField(Address, related_name='profiles', verbose_name='Адреса', null=True)
    phone = models.CharField(verbose_name='Телефон', max_length=100, unique=True)
    sms_code = models.CharField(verbose_name='СМС код', max_length=100, default=0)
    account_type = models.IntegerField(verbose_name='Тип аккаунта', default=1, choices=ACCOUNT_TYPES)

    class Meta:
        verbose_name = 'профиль'
        verbose_name_plural = 'профили'

    def __unicode__(self):
        return self.user.username

    @property
    def email(self):
        return self.user.email

    def get_chats_with_user(self, user):
        chats = self.chats.select_related().filter(users=user)
        for c in chats:
            if c.users.count() == 2:
                return c
        return False

    def get_permissions_for_chat(self, chat_pk):
        if self.chats.filter(pk=chat_pk): return True
        else: return False

    def get_fullname(self):
        if self.shop.all():
            return self.shop.get().title
        else:
            return self.user.get_full_name()


class Shop(models.Model):
    profile = models.ForeignKey(UserProfile, related_name='shop', verbose_name='Профиль')
    title = models.CharField(verbose_name=u'Наименование', max_length=100, unique=True)
    slug = models.SlugField(verbose_name='Ссылка', unique=True, default='')
    parts = models.ManyToManyField('catalog.Part', related_name='shops', through='catalog.PartsInShop',
                                   verbose_name='Запчасти')

    def __unicode__(self):
        return u'{0}'.format(self.title)

    class Meta:
        verbose_name = 'магазин'
        verbose_name_plural = 'магазины'


class Client(models.Model):
    profile = models.ForeignKey(UserProfile, related_name='client', verbose_name='Профиль')

    def __unicode__(self):
        return u'{0}'.format(self.profile)

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'


class Chat(models.Model):
    users = models.ManyToManyField(UserProfile, related_name='chats', verbose_name='Собеседники')
    title = models.CharField(verbose_name='Тема', max_length=100, null=True, blank=True, default='')

    def __unicode__(self):
        return u'{0}'.format(self.pk)

    def get_channel_name(self):
        return 'channel'+self.pk

    class Meta:
        verbose_name = 'чат'
        verbose_name_plural = 'чаты'


class Post(models.Model):
    author = models.ForeignKey(UserProfile, related_name='posts', verbose_name='автор')
    title = models.CharField(verbose_name='Тема', max_length=255)
    ts_created = models.DateTimeField(verbose_name='Дата создания', default=datetime.now(), auto_now_add=True)
    ts_changed = models.DateTimeField(verbose_name='Дата изменения', default=datetime.now(), auto_now=True, auto_now_add=True)
    ts_public = models.DateTimeField(verbose_name='Дата публикации', null=True, blank=True)
    content = models.TextField(verbose_name='Текст', max_length=10000)
    is_public = models.BooleanField(verbose_name='Статус публикации', default=False)
    slug = models.SlugField(verbose_name='Ссылка', default='', max_length=160)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return "/blogs/"+str(self.author.pk)+"/" + self.slug

    class Meta:
        verbose_name = 'пост'
        verbose_name_plural = 'посты'


class PostComment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', verbose_name='Пост')
    ts_created = models.DateTimeField(verbose_name='Дата создания', default=datetime.now(), auto_now_add=True)
    user = models.ForeignKey(UserProfile, related_name='post_comments', verbose_name='Адресант')
    answer_to = models.ForeignKey('self', related_name='post_answers',  null=True, blank=True, verbose_name='Адресат')
    text = models.CharField(verbose_name='Текст', max_length=10000)
    is_public = models.BooleanField(verbose_name='Статус публикации', default=True)

    def __unicode__(self):
        return self.text

    class Meta:
        verbose_name = 'комментарий'
        verbose_name_plural = 'комментарии'
        ordering = ['ts_created']

catalog/models.py
#coding: utf-8

from django.db import models
from accounts.models import *
from django.core.exceptions import ValidationError

TYPE_CHOICES = (
    (0, u'Новый'),
    (1, u'Б\У'),
)


class Part(models.Model):
    article = models.CharField(verbose_name='Артикул', max_length=100, default='', null=False, blank=False)
    slug = models.SlugField(verbose_name='Ссылка', unique=False, db_index=True)
    title = models.CharField(verbose_name='Наименование', max_length=100, default='', null=False)

    class Meta:
        verbose_name = 'Запчасть'
        verbose_name_plural = 'Запчасти'

    def __unicode__(self):
        return u'{0} ({1})'.format(self.title, self.article)


class PartsInShop(models.Model):
    part = models.ForeignKey(Part, related_name='ps_parts', verbose_name='Запчасть')
    shop = models.ForeignKey('accounts.Shop', related_name='ps_shops', verbose_name='Магазин')
    count = models.IntegerField(verbose_name='Количество', max_length=100, default=0)
    price = models.DecimalField(verbose_name='Стоимость', max_digits=9, decimal_places=2)
    type = models.IntegerField(verbose_name='Тип', max_length=1, choices=TYPE_CHOICES, default=0)

    class Meta:
        verbose_name = u'Запчасть а магазине'
        verbose_name_plural = u'Запчасти в магазине'

    def __unicode__(self):
        return u'{0} ({1} {2})'.format(self.shop, self.part, self.type)

delivery/models.py
#coding: utf-8
from django.db import models
from catalog.models import *
from accounts.models import *


TYPE_CHOICES = (
    ('ts_accept', 'В обработке'),
    ('ts_buy', 'Оплаченный'),
    ('ts_ended', 'Завершенный'),
    ('ts_created', 'В ожидании'),
)


SHIP_CHOICES = (
    ('td_pickup', 'Самовывоз'),
    ('td_courier', 'Курьерская доставка'),
)


PAY_CHOICES = (
    ('tp_cash', 'Наличный расчет'),
    ('tp_card', 'Оплата банковской картой'),
    ('tp_direct', 'Прямой перевод'),
)


STATE_CHOICES = (
    ('pd_created', 'В обработке'),
    ('pd_ship', 'Готов к отправке'),
    ('pd_fail', 'Отказано'),
)


class Delivery(models.Model):
    parts_in_del = models.ManyToManyField('catalog.PartsInShop', related_name='dd_parts', through='delivery.PartInDelivery', verbose_name=u'Запчасть')
    client_del = models.ForeignKey('accounts.UserProfile', verbose_name=u'Клиент', related_name='dd_client', null=True, blank=False, default=None)
    payment = models.CharField(verbose_name=u'Оплата', max_length=10, choices=PAY_CHOICES, default=0)
    shipping = models.CharField(verbose_name=u'Доставка', max_length=10, choices=SHIP_CHOICES, default=0)
    state = models.CharField(verbose_name=u'Статус', max_length=10, choices=TYPE_CHOICES)
    amount = models.DecimalField(verbose_name=u'Стоимость', max_digits=9, decimal_places=2, default=0)
    address = models.ForeignKey('accounts.Address', related_name='d_address', verbose_name=u'Адрес доставки', null=True, blank=True, default=None)

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __unicode__(self):
        return u'{0}'.format(self.client_del)


class PartInDelivery(models.Model):
    part_del = models.ForeignKey('delivery.Delivery', related_name='ps_del', verbose_name='Заказ', blank=True, null=True, default=None)
    part_in_shop = models.ForeignKey('catalog.PartsInShop', related_name='ps_part_in_del', blank=True, null=True, default=None, verbose_name='Запчасть в заказе')
    quantity = models.IntegerField(verbose_name=u'Количество', max_length=100, default=0)
    del_in_shop = models.ManyToManyField('accounts.Shop', related_name='pd_dis', blank=True, null=True, default=None, verbose_name='Заказ на запчасть в магазине')
    state_in_part = models.CharField(verbose_name='Статус запчасти', max_length=15, choices=STATE_CHOICES)


    class Meta:
        verbose_name = u'Запчасть в заказе'
        verbose_name_plural = u'Запчасти в заказе'

    def __unicode__(self):
        return u'{0}'.format(self.quantity)

accounts/forms.py
# -*- coding: utf-8 -*-
from django import forms
import re
from django.contrib.auth.models import User
from accounts.models import ACCOUNT_TYPES, Address, Shop
from ckeditor.widgets import CKEditorWidget


class AuthSendSmsForm(forms.Form):
    phone = forms.CharField(label=u'Номер телефона', max_length=12)

    def clean_phone(self):
        number = self.cleaned_data['phone']
        raw_number = re.sub('[^0-9]', u'', str(number.encode('utf-8')))
        if len(raw_number) < 10 or len(raw_number) > 11:
            raise forms.ValidationError(u'Неверный формат номера телефона')
        elif len(raw_number) == 11:
            if raw_number.startswith('8') or raw_number.startswith('7'):
                raw_number = raw_number[1:]
        return '7' + raw_number


class AuthRegistrationForm(forms.Form):
    email = forms.EmailField(label=u'Email', max_length=100)
    first_name = forms.CharField(label=u'Имя', max_length=100)
    last_name = forms.CharField(label=u'Фамилия', max_length=100)
    account_type = forms.ChoiceField(label=u'Тип аккаунта', choices=ACCOUNT_TYPES, help_text=u'Покупатель может только покупать, а продавец покупать и продавать.')


class AuthInputCodeForm(forms.Form):
    code = forms.CharField(label=u'Полученный код', max_length=100)


class DialogsForm(forms.Form):
    message = forms.CharField(label=u'Сообщение', max_length=10000)


class AddPartForm(forms.Form):
    article = forms.CharField(label=u'Артикул', max_length=100)
    title = forms.CharField(label=u'Наименование', max_length=100)
    price = forms.IntegerField(label=u'Стоимость', max_value=100000)
    count = forms.IntegerField(label=u'Колличество', max_value=100000)
    type = forms.CheckboxInput()


class AddPostForm(forms.Form):
    title = forms.CharField(label='Тема', max_length=255)
    content = forms.CharField(widget=CKEditorWidget(), label='Текст', max_length=10000)


class StatePartDelForm(forms.Form):
    accept = forms.CheckboxInput()


class EditUserDataForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name']
        error_messages = {
            'email': {
                'invalid': "Некорректный адрес электронной почты.",
            },
        }


class EditAddressesDataForm(forms.ModelForm):
    class Meta:
        model = Address


class EditShopDataForm(forms.ModelForm):
    class Meta:
        model = Shop
        fields = ['title',]

delivery/forms.py
#coding: utf-8
from django import forms
from django.forms.widgets import RadioSelect
from accounts.models import *
from delivery.models import *


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address


class ShippingForm(forms.ModelForm):
    class Meta:
        model = Delivery
        fields = ('shipping',)
        widgets = {
            'shipping': RadioSelect,
        }


class PaymentForm(forms.ModelForm):
    class Meta:
        model = Delivery
        fields = ('payment',)

templates/accounts/checkout_cart.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block title %}
Потверждение данных
{% endblock %}
{% block content %}
<br/><br/><br/><br/>
<form method="POST" name="RadioShippingForm" action="">
<div class="col-lg-12 row">
    <div class="panel panel-warning">
        <div class="panel-heading">
            <h4>Выбор данных для заказа</h4>
        </div>
        <div class="panel-body">
            <div class="col-md-6">
            {% csrf_token %}
            {% bootstrap_form ShippingForm %}
            </div>
            <div class="col-md-6">
                {% csrf_token %}
                {% bootstrap_form PaymentForm %}
            </div>
    <div class="col-md-12">
    <div class="" id="adr" style="display:block" >
    <div class="center-block"><h5>Выберите адресс, либо создайте новый</h5></div>
        <div class="list-group">
            {% for object in object_list %}
                <a class="list-group-item col-xs-6" style="margin-bottom: 10px; height: 130px">
                    {{ object.get_city_display }},
                    {{ object.address }}<br/>
                    Почтовый индекс: {{ object.address_index }}<br/>
                    {% if object.details %}Примечание: {{ object.details }}{% endif %}
                    {% buttons %}
                        <button type="submit" class="btn bottom" name="checkout_btn_{{ object.id }}" style="">Продолжить</button>
                    {% endbuttons %}
                </a>
            {% endfor %}
        </div>
            <div class="panel-group col-md-10 row">
              <div class="panel success">
                  <h4 class="panel-warning">
{#                    <a data-toggle="collapse" data-parent="#accordion" href="#bottom">#}
                        Добавить новый адрес
{#                    </a>#}
                  </h4>
                <div id="bottom" class="panel-collapse">
                  <div class="panel-body">
                    {% csrf_token %}
                    {% bootstrap_form AddresShipForm layout='panel' %}
                    {% buttons %}
                        <button type="submit" class="btn" name="checkout_btn_new" >Продолжить</button>
                    {% endbuttons %}
                  </div>
                </div>
              </div>
            </div>
        </div>
    </div>
  </div>
</div>
</div>
</div>
<div class="col-md-4">
    {% csrf_token %}
    {% buttons %}
        <button type="submit" class="btn btn-danger center-block" name="checkout_btn" id="bbb">Продолжить</button>
    {% endbuttons %}
</div>
</form>
{% endblock %}

templates/accounts/ckeditor_error.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
Изображение не может быть больше 5 мб!
</body>
</html>

templates/accounts/delivery.html
{% extends 'accounts/base.html' %}
{% block title %}
Мои заказы
{% endblock %}
{% block cabinet_content %}
    {% if object_list %}
        {% load pagination_tags %}
        {% autopaginate object_list 7 %}
        {% for object in object_list %}
            <div class="panel-group" id="accordion">
              <div class="panel {% if object.state == 'ts_created' %}panel-warning
                                {% elif object.state == 'ts_accept'%}panel-danger
                                {% elif object.state == 'ts_buy'%}panel-success
                                {% else %}panel-default{% endif %}">
                <div class="panel-heading">
                    <a data-toggle="collapse" data-parent="#accordion" href="#{{ object.id }}" class="btn">
                        <div class="text-left">
                            <b>Номер заказа:</b> {{ object.id }}<br/>
                            <b>Статус заказа:</b> {{ object.get_state_display }}<br/>
                            <b>Сумма заказа:</b> {{ object.amount }}
                        </div>
                    </a>
                </div>
                <div id="{{ object.id }}" class="panel-collapse collapsing">
                  <div class="panel-body">
                    <table class="table table-striped">
                    <thead>
                                <tr>
                                    <th>Артикул</th>
                                    <th>Наименование</th>
                                    <th>Кол-во</th>
                                    <th>Стоимость</th>
                                    <th>Тип</th>
                                </tr>
                    </thead>
                    <tbody>
                    {% for part in object.parts_in_del.all %}

                                <tr>
                                    <td><a class="text-warning" href="{% url 'account_order_detail' object.pk %}" data-toggle="tooltip">
                                            {{ part.part.article }}
                                        </a>
                                    </td>
                                    <td>{{ part.part.title}}</td>
                                    <td>{{ part.ps_part_in_del.first.quantity}}</td>
                                    <td>{{ part.price}}</td>
                                    <td>{{ part.get_type_display}}</td>
                                </tr>

                    {% endfor %}
                    </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
        {% endfor %}{% paginate %}
        {% else %}
        <p>У вас отсутствуют заказы.</p>
        <div class="alert alert-info" role="alert">
        Для того, чтобы оформить заказ, найдите нужную вам деталь по артикулу и добавьте в корзину.<br/>
        <a href="{% url 'search_by_article' %}" class="alert-link">Ссылка на поиск</a><br/>
        <a href="{% url 'catalog_part' %}" class="alert-link">Ссылка на каталог</a>
        </div>
    {% endif %}
{% endblock %}

templates/accounts/order_detail.html
{% extends 'accounts/base.html' %}
{% block title %}
Описание {{ object.title }}
{% endblock %}
{% block cabinet_content %}
    <div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h2 class="text-center">Заказ №{{ object.id }}</h2>
        <br/>
    <table class="table table-hover table-bordered">
    <tbody>
    <tr>
        <th>Статус заказа:</th>
        <td class="text-right">{{ object.get_state_display }}</td>
    </tr>
    <tr>
        <th>Способ оплаты:</th>
        <td class="text-right">{{ object.get_payment_display }}</td>
    </tr>
    <tr>
        <th>Тип доставки:</th>
        <td class="text-right">{{ object.get_shipping_display }}</td>
    </tr>
    {% if object.shipping == 'td_courier' %}
    <tr>
        <th>Адресс доставки:</th>
        <td class="text-right">{{ object.address }}</td>
    </tr>
    {% endif %}
    </tbody>
    </table>
    <h3 class="text-center">Список деталей в заказе</h3>
                    <table class="table table-striped">
                    <thead>
                                <tr>
                                    <th>Артикул</th>
                                    <th>Наименование</th>
                                    <th>Кол-во</th>
                                    <th>Стоимость</th>
                                    <th>Тип</th>
                                </tr>
                    </thead>
                    <tbody>
                    {% for part in object.parts_in_del.all %}

                                <tr>
                                    <td>{{ part.part.article}}</td>
                                    <td>{{ part.part.title}}</td>
                                    <td>{{ part.ps_part_in_del.first.quantity}}</td>
                                    <td>{{ part.price}}</td>
                                    <td>{{ part.get_type_display}}</td>
                                </tr>

                    {% endfor %}
                    </tbody>
                    </table>
    </div>
    </div>
{% endblock %}

templates/accounts/part_delivery.html
{% extends 'accounts/base.html' %}
{% block title %}
Просмотр запчастей в заказах
{% endblock %}
{% block cabinet_content %}
{% if order_list %}
<h3 class="text-center">Список заказаных у вас запчастей</h3><br/>
    <div class="right panel panel-danger">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Артикул</th>
                    <th>Наименование</th>
                    <th>Кол-во</th>
                    <th>Статус</th>
                    <th>Статус заказа</th>
                </tr>
            </thead>
{% load pagination_tags %}
{% autopaginate order_list 20 %}
            <tbody>
                {% for order in order_list %}
                    {% if order.part_del.state != 'ts_ended' %}
                        <tr>
                            <td>{{ order.part_in_shop.part.article }}</td>
                            <td>{{ order.part_in_shop.part.title }}</td>
                            <td>{{ order }}</td>
                            <td>
                                {% if order.state_in_part == 'pd_ship' %}
                                    <b class="text-info">Готово к отправке</b>
                                {% elif order.state_in_part == 'pd_fail' %}
                                    <b class="text-danger">Отсутствует</b>
                                {% else %}
                                <form action="{% url 'part_delivery' %}" method="post">{% csrf_token %}
                                    <button type="submit" class="btn btn-default btn-xs btn-info" name="ok"
                                            value="{{ order.id }}" title="Потверждение смены статуса">
                                        <span class="glyphicon glyphicon-ok"></span>
                                    </button>
                                    <input type="checkbox" title="Нажмите для сообщения о готовности отправки детали">
                                    <button type="submit" class="btn btn-default btn-xs btn-danger" name="fail"
                                            value="{{ order.id }}" title="Потверждение смены статуса">
                                        <span class="glyphicon glyphicon-remove"></span>
                                    </button>
                                </form>
                                {% endif %}
                            </td>
                            <td>{{ order.part_del.get_state_display }}</td>
                        </tr>
                    {% endif %}
                {% endfor %}
            </tbody>
        </table>
        <a data-toggle="collapse" data-parent="#accordion" href="#a6" class="panel-warning ">
            <div class="panel-heading">
                  <h4 class="">
                        <b>Проданные запчасти в количестве: {{ end_part }} шт.</b>
                  </h4>
            </div>
        </a>
            <div id="a6" class="panel-collapse collapsing">
                <div class="panel-body">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>Артикул</th>
                                <th>Наименование</th>
                                <th>Кол-во</th>
                                <th>Статус заказа</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for order in order_list %}
                                {% if order.part_del.state == 'ts_ended' %}
                                    <tr>
                                        <td>{{ order.part_in_shop.part.article }}</td>
                                        <td>{{ order.part_in_shop.part.title }}</td>
                                        <td>{{ order }}</td>
                                        <td>{{ order.part_del.get_state_display }}</td>
                                    </tr>
                                {% endif %}
                            {% endfor %}
                        </tbody>
                    </table>
              </div>
        </div>
    </div>{% paginate %}
{% else %}
    У вас запчасти еще не покупали
{% endif %}
<br/>
{% endblock %}